server:
  port: 8083

  
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: Santhosh@18
    url: jdbc:mysql://localhost:3306/microservices
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: RATING-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true